planner_frequency: 20
recovery_behavior_enabled: true

TrajectoryPlannerROS:

  max_vel_x: 0.5
  min_vel_x: 0.01
  max_vel_theta: 1.5
  min_in_place_vel_theta: -1.5
  escape_vel: 1

  acc_lim_theta: 1.5
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  meter_scoring: true

  holonomic_robot: false



